TARGET = RoadKill
OBJS = froggy.o roadkill.o

CFLAGS = -O2 -G0 -Wall
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

PSPBIN = $(PSPSDK)/../bin
CFLAGS += `$(PSPBIN)/sdl-config --cflags`
LIBS +=-lmxf  `$(PSPBIN)/sdl-config --libs`  -lpsppower

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = Road Kill
 #PSP_EBOOT_ICON = alpha.png
 #PSP_EBOOT_PIC1 = img3.png

PSPSDK=$(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak


 
